In [ ]:
import numpy as np

In [6]:
# Load only numeric marks (columns 1 to 5), skip header row, skip name column
marks = np.genfromtxt('sample_data.csv', delimiter=',', skip_header=1, usecols=(1,2,3,4,5))

# Load only names column separately
names = np.genfromtxt('sample_data.csv', delimiter=',', skip_header=1, usecols=0, dtype=str)

print("Names:", names)
print("Marks:\n", marks)
print("Shape:", marks.shape)

Names: ['Amit' 'Riya' 'Karan' 'Neha' 'Suresh' 'Pooja' 'Vikas' 'Anjali' 'Rohit'
 'Sneha' 'Arjun' 'Divya']
Marks:
 [[85. 90. 78. 88. 92.]
 [70. 65. 80. 75. 60.]
 [55. 60. 58. 62. 50.]
 [95. 92. 89. 97. 94.]
 [40. 45. 38. 50. 42.]
 [77. 82. 75. 80. 79.]
 [60. 55. 65. 58. 62.]
 [88. 85. 90. 87. 91.]
 [65. 70. 68. 72. 66.]
 [72. 75. 70. 78. 74.]
 [50. 55. 48. 52. 49.]
 [90. 88. 93. 91. 89.]]
Shape: (12, 5)


In [31]:
stu = np.average(marks, axis=1)  # Calculate average marks for each student (row-wise)
 

# Single highest/lowest mark in entire dataset (not average)
highest_mark = np.max(marks)
lowest_mark = np.min(marks)

# Find WHICH student and subject
row, col = np.unravel_index(np.argmax(marks), marks.shape)
print(f"Highest mark: {highest_mark} by {names[row]} in subject{col+1}")

row, col = np.unravel_index(np.argmin(marks), marks.shape)
print(f"Lowest mark: {lowest_mark} by {names[row]} in subject{col+1}")

Highest mark: 97.0 by Neha in subject4
Lowest mark: 38.0 by Suresh in subject3


In [32]:
conditions = [stu >= 90, stu >= 80, stu >= 70, stu >= 60]
choices = ['A', 'B', 'C', 'D']
grades = np.select(conditions, choices, default='F')

for i in range(len(names)):
    print(f"{names[i]} -> avg: {stu[i]:.2f}, grade: {grades[i]}")

Amit -> avg: 86.60, grade: B
Riya -> avg: 70.00, grade: C
Karan -> avg: 57.00, grade: F
Neha -> avg: 93.40, grade: A
Suresh -> avg: 43.00, grade: F
Pooja -> avg: 78.60, grade: C
Vikas -> avg: 60.00, grade: D
Anjali -> avg: 88.20, grade: B
Rohit -> avg: 68.20, grade: D
Sneha -> avg: 73.80, grade: C
Arjun -> avg: 50.80, grade: F
Divya -> avg: 90.20, grade: A


In [34]:
# argsort default ascending deta hai, isliye reverse karna padega
sorted_indices = np.argsort(stu)[::-1]   # descending order ke indices

# Top 3
print("Top 3 Performers:")
for i in sorted_indices[:3]:
    print(f"{names[i]} -> {stu[i]:.2f}")

# Full ranking
print("\nFull Ranking:")
for rank, i in enumerate(sorted_indices, start=1):
    print(f"Rank {rank}: {names[i]} -> {stu[i]:.2f}")

Top 3 Performers:
Neha -> 93.40
Divya -> 90.20
Anjali -> 88.20

Full Ranking:
Rank 1: Neha -> 93.40
Rank 2: Divya -> 90.20
Rank 3: Anjali -> 88.20
Rank 4: Amit -> 86.60
Rank 5: Pooja -> 78.60
Rank 6: Sneha -> 73.80
Rank 7: Riya -> 70.00
Rank 8: Rohit -> 68.20
Rank 9: Vikas -> 60.00
Rank 10: Karan -> 57.00
Rank 11: Arjun -> 50.80
Rank 12: Suresh -> 43.00


In [38]:
sub_avg = np.average(marks, axis=0)  # Calculate average marks for each subject (column-wise)
sub_max = np.argmax(marks, axis=0)  # For each subject (column), find the index of the student with highest mark
print("\nTop Performers in Each Subject:")
for j, idx in enumerate(sub_max):
    print(f"Subject {j+1}: {names[idx]} with mark {marks[idx][j]}")
sub_min = np.argmin(marks, axis=0)  # For each subject (column), find the index of the student with lowest mark
print("\nLowest Performers in Each Subject:")
for j, idx in enumerate(sub_min):
    print(f"Subject {j+1}: {names[idx]} with mark {marks[idx][j]}")
sub_indices = np.argsort(sub_avg)[::-1]  # Sort subjects by average marks in descending order
print(f"Subjects toughest: Subject {sub_indices[-1] + 1}")
print(f"Subjects easiest: Subject {sub_indices[0] + 1}")


Top Performers in Each Subject:
Subject 1: Neha with mark 95.0
Subject 2: Neha with mark 92.0
Subject 3: Divya with mark 93.0
Subject 4: Neha with mark 97.0
Subject 5: Neha with mark 94.0

Lowest Performers in Each Subject:
Subject 1: Suresh with mark 40.0
Subject 2: Suresh with mark 45.0
Subject 3: Suresh with mark 38.0
Subject 4: Suresh with mark 50.0
Subject 5: Suresh with mark 42.0
Subjects toughest: Subject 1
Subjects easiest: Subject 4
